django_movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.flatpages import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include("contact.urls")),
    path("", include("movies.urls")),
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('index/', views.flatpage, {'url': '/index/'}, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
# from .views import FilterMoviesByRating
from . import views

urlpatterns = [
    path("", views.MoviesView.as_view()),
    path("filter/", views.FilterMoviesView.as_view(), name='filter'),
    path("search/", views.Search.as_view(), name='search'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path("json-filter/", views.JsonFilterMoviesView.as_view(), name='json_filter'),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name="movie_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail"),
    path("connection", views.ConnectionFormView.as_view(), name="connection"),
    path('about/', views.about_page, name='about_page'),
    path('index/', views.index_page, name='index_page'),
    path("filter/<int:star>/", views.FilterMoviesView.as_view(), name='filter_by_star'),
    # path('filter/<int:rating>/', FilterMoviesByRating.as_view(), name='filter_movies_by_rating'),

]

movies/models.py
from django.db import models
from datetime import date

from django.urls import reverse


class Category(models.Model):
    # Категории
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Actor(models.Model):
    # Персонажи и режиссеры
    name = models.CharField('Имя', max_length=100)
    age = models.PositiveIntegerField('Возраст', blank=True)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='actors/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = 'Персонаж и режиссер'
        verbose_name_plural = 'Персонажи и режиссеры'


class Genre(models.Model):
    # Жанры
    name = models.CharField('Имя', max_length=100)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Movie(models.Model):
    # Аниме
    title = models.CharField('Название', max_length=100)
    tagline = models.CharField('Слоган', max_length=100, default='')
    description = models.TextField('Описание')
    poster = models.ImageField('Постер', upload_to='movies/')
    year = models.PositiveSmallIntegerField('Дата выхода', default=2022)
    country = models.CharField('Страна', max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name='режиссер',
                                       related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='персонажи',
                                    related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='жанры')
    world_premiere = models.DateField('Премьера в мире', default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default=0,
                                         help_text='указывать сумму в долларах')
    category = models.ForeignKey(Category, verbose_name='Категория',
                                 on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = 'Аниме'
        verbose_name_plural = 'Аниме'


class MovieShots(models.Model):
    # Кадры из аниме
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение",
                              upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Аниме",
                              on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из аниме"
        verbose_name_plural = "Кадры из аниме"


class RatingStar(models.Model):
    # Звезда рейтинга
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    # Рейтинг
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar,
                             on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE,
                              verbose_name="аниме")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    # Отзывы
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL,
        blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name="аниме",
                              on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Feedback(models.Model):
    # обратная связь
    name = models.CharField(max_length=255)
    email = models.EmailField()
    content = models.TextField()

    def __str__(self):
        return f'{self.name} - {self.email}'

    class Meta:
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратная связь'

movies/forms.py
from django import forms

from .models import Reviews, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    # Форма отзывов
    class Meta:
        model = Reviews
        fields = ("name", "email", "text")


class RatingForm(forms.ModelForm):
    # Форма добавления рейтинга
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)


class ConnectionForm(forms.Form):
    # Форма обратной связи
    name = forms.CharField(max_length=255, label='Имя')
    email = forms.EmailField(label='Email')
    content = forms.CharField(label='Сообщение',
                              widget=forms.Textarea(attrs={'style': 'width:100%', 'rows': 10}))

movies/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.base import View
from django.urls import reverse_lazy
from .models import Movie, Category, Actor, Genre, Rating
from .forms import *

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.contrib.flatpages.models import FlatPage
from .forms import ConnectionForm
from .models import Feedback

# class FilterMoviesByRating(View):
#     # фильтр рейтинга
#     template_name = 'movies/movie_list.html'
#     paginate_by = 12
#
#     def get(self, request, rating):
#         filtered_movies = Movie.objects.filter(rating__star__value=rating)
#         context = {'movie_list': filtered_movies, 'selected_rating': rating}
#         return render(request, self.template_name, context)


def about_page(request):
    flatpage = FlatPage.objects.get(url='/about/')
    return render(request, 'pages/about.html', {'flatpage': flatpage})


def index_page(request):
    flatpage = FlatPage.objects.get(url='/index/')
    return render(request, 'pages/index.html', {'flatpage': flatpage})


class ConnectionFormView(View):
    template_name = 'contact/connection.html'
    success_url = reverse_lazy('about')

    def get(self, request, *args, **kwargs):
        form = ConnectionForm()
        context = {
            'title': "Обратная связь",
            'cat_selected': 2,
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = ConnectionForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            content = form.cleaned_data['content']

            # Save the feedback to the database
            feedback = Feedback(name=name, email=email, content=content)
            feedback.save()

            success_message = "Спасибо за обращение, мы рассмотрим его и обязательно Вас проинформируем."
            context = {
                'title': "Обратная связь",
                'cat_selected': 2,
                'form': form,
                'success_message': success_message,
            }
            return render(request, self.template_name, context)
        else:
            return render(request, self.template_name, {'form': form})


class GenreYear:
    # Жанры и года выхода аниме
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values("year").distinct().order_by("-year")


class MoviesView(GenreYear, ListView):
    # Список аниме
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    paginate_by = 9


class MovieDetailView(GenreYear, DetailView):
    # Полное описание аниме
    model = Movie
    slug_field = "url"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        return context


class AddReview(View):
    # Отзывы
    @method_decorator(login_required)  # Добавляем декоратор для проверки аутентификации
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    # Вывод информации о персонаже
    model = Actor
    template_name = 'movies/actor.html'
    slug_field = "name"


class FilterMoviesView(GenreYear, ListView):
    # Фильтр аниме
    model = Movie
    paginate_by = 9
    template_name = 'movies/movie_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()

        selected_stars = self.kwargs.get('star')
        if selected_stars is not None:
            queryset = queryset.filter(rating__star__value=selected_stars)

        years = self.request.GET.getlist("year")
        genres = self.request.GET.getlist("genre")

        if years:
            queryset = queryset.filter(year__in=years)

        if genres:
            queryset = queryset.filter(genres__in=genres)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        return context


class JsonFilterMoviesView(ListView):
    # Фильтр фильмов в json
    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct().values("title", "tagline", "url", "poster")
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({"movies": queryset}, safe=False)


class AddStarRating(View):
    # Добавление рейтинга аниме

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    # Поиск аниме
    paginate_by = 3

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>Возраст:</b> {{ actor.age }} лет</span></li>
                    <li style="list-style: none">
                        <span><b>Режиссер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>Актер:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                О {{ actor.name }}
            </h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
    </div>
{% endblock movie %}
</div>
</div>

templates/movies/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
<section class="ab-info-main py-md-5 py-4 editContent"
     style="padding-left: 3rem; padding-right: 3rem; background-image: url(../static/fon1.png);
            background-size: cover; background-position: center; background-color: rgba(255, 255, 255, 0.8);
            background-blend-mode: lighten;">
    {% block container %}
    <div class="container-fluid py-md-3">
    {% endblock container %}
    <div class="row">
    {% block sidebar %}
    <div class="side-bar col-lg-3">
    {% endblock sidebar %}
        {% include 'include/sidebar.html' %}
    </div>
        {% block movie %}
        {% endblock movie %}

        </div>
    </div>
</section>
{% endblock content %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load humanize %}
{% load static %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
<div class="container py-md-3">
    {% endblock container %}

    {% block sidebar %}
    <div class="side-bar col-lg-4">
        {% endblock sidebar %}

        {% block movie %}
        <div class="left-ads-display col-lg-8">
            <div class="row">
                <div class="desc1-left col-md-6">
                    <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                </div>
                <div class="desc1-right col-md-6 pl-lg-4">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                        {{ movie.title }}
                    </h3>
                    <h5 class="editContent"></h5>
                    <ul>
                        <li style="list-style: none">
                            <span><b>Год:</b> {{ movie.year }}</span></li>
                        <li style="list-style: none">
                            <span><b>Страна:</b> {{ movie.country }}</span>
                        </li>
                        <li style="list-style: none">
                            <span><b>Слоган:</b> {{ movie.tagline }}</span>
                        </li>
                        <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for director in movie.directors.all %}
                                            <a href="{{ director.get_absolute_url }}">
                                    {{ director.name }}
                                </a>
                                        {% endfor %}
                         </span>
                        </li>
                        <li style="list-style: none"><span><b>Персонажи:</b>
                                    {% for actor in movie.actors.all %}
                                        <a href="{{ actor.get_absolute_url }}">
                                    {{ actor.name }}
                            </a>
                                    {% endfor %}
                          </span>
                        </li>
                        <li style="list-style: none"><span><b>Жанр:</b>
                                    {% for genre in movie.genres.all %}
                                        {{ genre.name }}
                                    {% endfor %}
                                    </span>
                        </li>
                        <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                        </li>
                        <li style="list-style: none">
                            <span><b>Бюджет:</b> ${{ movie.budget|intcomma }}</span></li>
                        <li style="list-style: none">
                            <form action="{% url 'add_rating' %}" method="post" name="rating">
                                <b>Оцени аниме:</b>
                                {% csrf_token %}
                                <input type="hidden" value="{{ movie.id }}" name="movie">
                                <span class="rating">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            </form>
                        </li>
                    </ul>

                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent" style="outline: none; cursor: inherit;">Напишите нам:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
    <li class="share-circle">
        <a href="https://telegram.me/share/url?url=Your%20URL&text=Your%20Share%20Text"
           class="w3pvt_telegram editContent" style="outline: none; cursor: pointer;">
            <span class="fa fa-paper-plane" style="outline: none; cursor: pointer;"></span>
        </a>
    </li>
</ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class=" sub-para-w3layouts mt-5">

                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                    О фильме {{ movie.title }}
                </h3>
                <div class="row">
                    {% for image in movie.movieshots_set.all %}
                    <div class="col-4"><img src="{{ image.image.url }}" class="img-movie-shots"
                                            alt="{{ image.description }}"></div>
                    {% endfor %}
                </div>
                <p class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.description|safe }}
                </p>
            </div>
            <hr>
            <div class="row">
                <div class="single-form-left">
                    <!-- contact form grid -->
                    <div class="contact-single">
                        <h3 class="editContent" style="outline: none; cursor: inherit; margin-left: 20px;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">{{ movie.reviews_set.count }}</span>Оставить
                            отзыв</h3>
                        {% if user.is_authenticated %}  <!-- Проверяем, аутентифицирован ли пользователь -->
                        <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview"
                              style="margin-left: 20px;">
                            {% csrf_token %}
                            <input type="hidden" name="parent" id="contactparent" value="">
                            <div class="form-group editContent">
                                <label for="contactcomment" class="editContent">
                                    Ваш комментарий *
                                </label>
                                <textarea class="form-control border" rows="5" name="text"
                                          id="contactcomment" required=""></textarea>
                            </div>
                            <div class="d-sm-flex">
                                <div class="col-sm-6 form-group p-0 editContent">
                                    <label for="contactusername" class="editContent">
                                        Имя *
                                    </label>
                                    <input type="text" class="form-control border" name="name"
                                           id="contactusername" required="">
                                </div>
                                <div class="col-sm-6 form-group ml-sm-3 editContent">
                                    <label for="contactemail" class="editContent">
                                        Email *
                                    </label>
                                    <input type="email" class="form-control border" name="email"
                                           id="contactemail" required="">
                                </div>
                            </div>
                            <button type="submit"
                                    class="mt-3 btn btn-success btn-block py-3">
                                Отправить
                            </button>
                        </form>
                        {% else %}
                        <p>Чтобы оставить отзыв, пожалуйста, <a href="{% url 'account_login' %}">войдите</a> или <a
                                href="{% url 'account_signup' %}">зарегистрируйтесь</a>.</p>
                        {% endif %}
                    </div>
                    <!--  //contact form grid ends here -->
                </div>
            </div>
            {% for review in movie.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/te2.jpeg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview"
                       onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {% for rew in review.reviews_set.all %}
                    <div class="media mt-5 editContent">
                        <a class="pr-3" href="#">
                            <img src="{% static 'images/te2.jpeg' %}" class="img-fluid "
                                 alt="image">
                        </a>
                        <div class="media-body">
                            <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                            <p class="mt-2 editContent">{{ rew.text }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }



    </script>
    {% endblock movie %}
</div>

templates/movies/movie_list.html
{% extends 'movies/base.html' %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
<div class="left-ads-display col-lg-9">
    <div class="row">
        {% for movie in movie_list %}
        <div class="col-md-4 product-men">
            <div class="product-shoe-info editContent text-center mt-lg-4">
                <div class="men-thumb-item">
                    <a href="{{ movie.get_absolute_url}}" class="editContent"><img src="{{ movie.poster.url }}"
                                                                                   class="img-fluid" alt=""></a>
                </div>
                <div class="item-info-product">
                    <h4 class="">
                        <a href="{{ movie.get_absolute_url}}" class="editContent">
                            {{ movie.title }}
                        </a>
                    </h4>

                    <div class="product_price">
                        <div class="grid-price">
                            <span class="money editContent">{{ movie.tagline }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="grid-img-right mt-4 text-right bg bg1">
        {% include 'include/pagination.html' %}
    </div>
</div>
{% endblock movie %}